apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: production
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx
      containers:
        - name: nginx
          image: nginx:1.14.2          
          ports:
            - containerPort: 80
          volumeMounts:
            - name: my-api-token
              mountPath: /mnt/api-token
              readOnly: true
          env:
            - name: password
              valueFrom:
                secretKeyRef:
                  name: api-token
                  key: password
            - name: username
              valueFrom:
                secretKeyRef:
                  name: api-token
                  key: username
            - name: db
              valueFrom:
                secretKeyRef:
                  name: api-token
                  key: db
            - name: login
              valueFrom:
                secretKeyRef:
                  name: api-token
                  key: login
            - name: logo
              valueFrom:
                secretKeyRef:
                  name: api-token
                  key: logo                                                                           
      volumes:
        - name: my-api-token
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: aws-secrets

---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: production
spec:
  provider: aws
  secretObjects:
    - secretName: api-token
      type: Opaque
      data:
        - objectName: env
          key: logo    
        - objectName: env
          key: password
        - objectName: env
          key: username
        - objectName: env
          key: db
        - objectName: env
          key: login         
  parameters:
    objects: |
      - objectName: my-secrets
        objectType: secretsmanager
        objectAlias: env


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  namespace: production
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::068165388964:role/api-token-access






