apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: work
  region: us-east-2

managedNodeGroups:
- name: workgroup
  instanceType: t2.micro
  desiredCapacity: 2
  minSize: 2
  maxSize: 2
